package wsdl2java;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-04-20T12:43:11.180+04:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebServiceClient(name = "RequestProcess", 
                  wsdlLocation = "file:/C:/Users/Miganko/Documents/NetBeansProjects/CourseProj/emsim-client/src/main/resources/wsdl/RequestProcess.wsdl",
                  targetNamespace = "http://wsdl2java") 
public class RequestProcess extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wsdl2java", "RequestProcess");
    public final static QName RequestProcessPort = new QName("http://wsdl2java", "RequestProcessPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Miganko/Documents/NetBeansProjects/CourseProj/emsim-client/src/main/resources/wsdl/RequestProcess.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RequestProcess.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Miganko/Documents/NetBeansProjects/CourseProj/emsim-client/src/main/resources/wsdl/RequestProcess.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RequestProcess(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RequestProcess(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RequestProcess() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RequestProcess(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RequestProcess(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RequestProcess(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns RequestProcessService
     */
    @WebEndpoint(name = "RequestProcessPort")
    public RequestProcessService getRequestProcessPort() {
        return super.getPort(RequestProcessPort, RequestProcessService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RequestProcessService
     */
    @WebEndpoint(name = "RequestProcessPort")
    public RequestProcessService getRequestProcessPort(WebServiceFeature... features) {
        return super.getPort(RequestProcessPort, RequestProcessService.class, features);
    }

}
